### ISSUE TITLE
Partition is not always the best fit.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#190] opened 2012-03-13 23:37 UTC
See sample in: samples / test / partition-bad-fit

**Expected:**
The smaller partition size is a better fit for the prop.

**Actual:**
It is using one size larger than it needs to.

**Additional Info:**
In the sample the prop starts with a rotation of 360 degrees. This bug happens frequently, though not always, when the prop is rotated by a multiple of 90 degrees.

**Comment by patrickmeehan** [comment] 2012-03-16 23:19
So this is actually not a bug per se. There are small errors introduced when rotating be certain angles. Since the prop is tight-fitted to the partition size, even a tiny error will push it over. I'm going to close this issue and open a new one (not a bug) to check into floating point errors.

**Closed as completed by patrickmeehan** 2012-03-16 23:19 UTC
Labels: Bug
