### ISSUE TITLE
A lot of missing getters

### ISSUE THREAD

**Issue by vertti** [moai/moai-dev#693] opened 2013-05-05 07:23 UTC
Why is MOAI API's full of setters with no getters?

MOAIProp.setVisible but no isVisible?
MOAIProp.setBlendMode but no getBlendMode?
MOAIBox2DBody.setLinearDamping but no getLinearDamping?

etc etc etc ...

Now many things like saving state etc need extra data keeping in places where it should not be.

**Comment by superquadratic** [comment] 2013-08-28 09:39
Duplicate of #566.

**Closed as completed by superquadratic** 2013-08-28 09:39 UTC
