### ISSUE TITLE
seekLoc on a layer isn't transforming the props correctly

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#185] opened 2012-03-10 00:18 UTC
See sample in master branch: samples / test / partition-seekloc

This bug was reported at: http://getmoai.com/forums/partition-moving-t555/

**Expected:**
When the layer is moved, the positions of the buttons should move properly.

**Actual:**
Clicking in the same spot after the seek starts or completes will output that you're still clicking on the same button, even though the button has moved. With the debug info for the partition shown, sometimes some ghost partitions will flash on the screen if you move your cursor over the window.

**Comment by patrickmeehan** [comment] 2012-03-17 00:17
Hey, could you move this to integration branch and send back to me?

**Comment by danadrew** [comment] 2012-03-17 00:29
I've moved the sample into the integration branch in: samples / test / partition-seekLoc and I updated the sample so it'll work with the new implementations on integration.

**Comment by patrickmeehan** [comment] 2012-03-17 01:25
Turns out the transform bug and the 'ghost' debug lines were unrelated. Both should be fixed now.

**Comment by danadrew** [comment] 2012-03-17 01:51
The buttons' positions seem to lag a bit behind now if you try to click on them while they're moving.

If you click on button 2 so they move off to the left, keep your cursor in the same spot and then click again on button 3 when it's passing by, it will still print out that you clicked on button 2. If you click again after all the buttons have passed, it will print that button 3 was pressed.

It doesn't seem to be that the positions aren't updated until the action is completed, but it really looks like they just lag behind somehow.

**Comment by patrickmeehan** [comment] 2012-03-21 04:42
OK, turns out the problem was in the test. Since the pointer location only gets updated and taken into the layer's local space when it actually moves, the point was stale by the time the click event occurred. In other words, if you click to start the layer sliding and then hold your pointer steady, the original location would never change and effectively 'travel' with the layer. I fixed this by polling the pointer location in the click callback and transforming it again, so it will always be fresh.

So... this should work now. You may still want to update this test to also support touch input.

**Comment by danadrew** [comment] 2012-03-21 21:39
The sample now crashes on exit if you click button 1 and then close the application. Possible error in the sample again? I couldn't find anything that could be causing it, though.

**Comment by patrickmeehan** [comment] 2012-03-27 00:04
We weren't able to reproduce this. It would sometimes crop up after a git checkout, but go away with a clean build. Looked at it in the debugger and the behavior seemed to indicate a stale .obj file. Closing for now.

**Closed as completed by patrickmeehan** 2012-03-27 00:04 UTC
Labels: Bug
