### ISSUE TITLE
ant/libmoai-build.sh requires these workarounds

### ISSUE THREAD

**Issue by mmontvai** [moai/moai-dev#1106] opened 2015-04-08 22:55 UTC
Using lubuntu-14.10-desktop-amd64, Oracle JDK 1.7, both Android NDK r8e and r9d
Downloaded the develop branch on 2015.04.08, unpacked renamed to moai-dev, environment is set up properly
cd moai-dev/ant
./libmoai-build.sh 
throws multiple errors, all have workaround
1. multiple references for **AKUPluginsAppFinalize** (and 3 others)
   - go to **\moai-dev\ant\libmoai\jni\src\**
   - edit **aku_plugins.cpp** → comment out all functions (maybe this is not the best solution)
2. undefined reference to eglGetProcAddress
   - edit the **\moai-dev\ant\libmoai\jni\Android.mk**
   - ensure line 24 is appended with -lEGL, resulting: **LOCAL_LDLIBS := -llog -lGLESv1_CM -lGLESv2 -lEGL**
3. MOAIImage.cpp:1920: undefined reference to 'edtaa3' and undefined reference to 'computegradient' 
   - edit the **\moai-dev\ant\libmoai\modules\3rdparty-contrib.mk**
   - add line: **LOCAL_SRC_FILES += $(MOAI_SDK_HOME)/3rdparty/contrib/edtaa3func.c**

**Comment by ghost** [comment] 2015-04-08 23:58
What about not messing around with changing stuff like directories names or cmake files?Not trying to be rude here but cmake is not something you want to play with :).I'd recomand downloading the 1.5-stable and build it normally!

**Comment by mmontvai** [comment] 2015-04-09 07:21
1. It does not work. I downloaded, unpacked and followed every single step believe me I want to use it the official way, but it just not work. Either the documentation is incorrect, or something is not right in my env, but please consider that I even tried to build on Windows 7 system, Ubuntu and lubuntu virtual machines. They ALL fail.
2. The **CMAKE way works** until building the library, but then the referenced "release" directory **is not created, not existing** although it should according to the official guide:
   - cd release/android/host
   - vi settings-global.sh
   - vi settings-local.sh
3. My suggestion was related to the **ANT build** not to the CMAKE. 
   - I think the **contrib/edtaa3func** file is new and left out accidentaly, as all other sources are in the mk file, furthermore it fixes a bunches of error messages during compilation
   - The Android.mk is clearly missing the -lEGL parameter, as it fixes other bunch of compilation errors
   - Only the jni workaround is suspicious for me, but without it the compilation will

Anyway I just wanted to raise these because it took me hours hunt them down and wanted to help the development.

I try to build Android host since December, and tried a lot of versions/packages without any success, therefore we ported our really simple game to another engine, but I still think that MOAI is really aligned to our needs, so I wanted to give it another try.

**Comment by halfnelson** [comment] 2015-04-09 07:42
Hi mmontvai, thanks for the report. The documentation for 1.6 is indeed out of date. The building of the android host is now done in two parts. The first is via the bin/build-android.sh/bat script. This will create a lib folder in the sdk root that contains an android subfolder with armeabi, armeabiv7a and x86 versions of the moai libraries (as static libs).

Once you have the moai android binaries you can create a host. To do this you can use the moaiutil script in the util folder. Make sure you have built moai for your host operating system (windows is bin/build-windows.bat), this will create a moai.exe in the util folder which is needed to run the moaituil script.

you can then create an android host for your app by running `moaiutil host-android-gradle`, or you can use the new `moaiutil host` commands outlined here : https://github.com/moai/moai-dev/pull/1066

I am still writing up more documentation on this method. there is some here https://github.com/moai/moai-dev/blob/develop/docs/building/On%20Windows.md which is mostly accurate but doesn't outline the handy `moaiutil host` command.

the main difference is all libs are built with cmake, then using lua scripts run via moai (`moaiutil`) you generate hosts for your project. the hosts can symlink the libs or take a copy of the libs. The hosts using the `moaiutil host` command are nice and configurable without massive rebuilds, you can change app name, icon, etc from the hostconfig.lua and regenerate the host from that so you don't even need to store the host project in version control.

**Comment by halfnelson** [comment] 2015-04-09 07:54
the continuous integration script for linux builds the android host and is currently building without problems. here is the script for reference https://github.com/moai/moai-dev/blob/c79f2e6394b1734265a03809ab6a7790afcc84f7/bin/ci-linux.sh

**Comment by mmontvai** [comment] 2015-04-09 11:19
Thank you for the response, unfortunately I missed the moaiutil command indeed. I will check it as soon as possible.
I think my report in this case can be closed if you agree.
The new and official way to build MOAI seems to be clear for me now.
Thank you very much for the deatiled and quick answer.

**Comment by seclorum** [comment] 2015-04-09 11:53
Please don't close this ticket until its confirmed that you can build the Android host with moaiutil.

**Comment by mmontvai** [comment] 2015-04-09 19:44
I followed the steps you detailed with the version I downloaded 2015.04.08.
- I successfully built libs with **bin/build-android.sh** and **bin/build-linux.sh** (using lubuntu in VirtualBox)
- I failed to create host using **moaiutil host-android-gradle**, the output:

Moai SDK 1.6 (ad hoc build by <unknown>)
main.lua:161: attempt to concatenate local 'configFile' (a boolean value)
stack traceback:
    [C] in function '__concat'
    main.lua:161 in function 'applyConfigFile'
    main.lua:330 in main chunk
    [C] in function 'dofile'
    moaiutil.lua:15 in main chunk
-  I failed with **moaiutil host init** followed by **moaiutil host create android-gradle**, the result:

Moai SDK 1.6 (ad hoc build by <unknown>)
creating host: android-gradle
/home/xy/moai/moai-dev/util/moaiutil: 10: /home/xy/moai/moai-dev/util/moaiutil: pushd: not found
reading config from /home/xy/moai/moai-dev/util/hostconfig.lua
Your configured lua path does not contain a main.lua
configured path (absolute):     /home/xy/moai/moai-dev/util/src/
/home/xy/moai/moai-dev/util/moaiutil: 12: /home/xy/moai/moai-dev/util/moaiutil: popd: not found

 Host created 
- Although it writes that Host created, there is no host created.
- I did a quick test with moai-dev-Version-1.5.2 for reference, but it failed to compile with **bin/build-android.sh** (I had this issue a few month ago, that's why I started to play with the Ant build which I could tweak to compile, but never was able to start on phone or Android emulator)

Linking C static library /home/xy/moai/moai-dev/ant/libmoai/libs/armeabi-v7a/libcrypto.a
[ 42%] Built target crypto
CMakeFiles/Makefile2:2327: recipe for target 'host-android/CMakeFiles/moai.dir/rule' failed
make[1]: **\* [host-android/CMakeFiles/moai.dir/rule] Error 2
make: **\* [moai] Error 2
Makefile:613: recipe for target 'moai' failed
- I built 1.5.1 with **bin/build-android.sh** successfully then in the **ant/untitled-host/** folder I edited the setting files, ran the run-host.sh, finally the app is installed but it crashes immediately after starting in emu.

**Comment by halfnelson** [comment] 2015-04-09 21:40
looks like host-android-gradle util wants a config file, that is a regression and I will fix it. It looks like the moaiutil script assumes bash as a default shell, can you try adding `#!/usr/bin/env bash` to the first line of `/util/moaiutil` and try again.

it was throwing an error saying it couldn't find main.lua in your lua source path. this is a setting in the generated config file. Could you try the bash fix and try again please? `moaiutil host create android-gradle`

**Comment by mmontvai** [comment] 2015-04-10 07:02
I added the line you mentioned and checked both ways
- `moaiutil host-android-gradle` - same result as above: 

main.lua:161: attempt to concatenate local 'configFile' (a boolean value)
...
- `moaiutil host create android-gradle` - a step forward: 

It created a `android-gradle` folder with some content though it failed at some point:
main.lua:161: attempt to concatenate local 'configFile' (a boolean value)
stack traceback:
    [C] in function '__concat'
    main.lua:161 in function 'applyConfigFile'
    main.lua:330 in main chunk
    [C] in function 'dofile'
    moaiutil.lua:15 in main chunk

The second way worked only when I had a folder named `src` with a main.lua in it, without it the script fails immediately:

reading config from /home/xy/moai/moai-dev-develop-20150408/mm3/hostconfig.lua
Your configured lua path does not contain a main.lua
configured path (absolute):     /home/xy/moai/moai-dev-develop-20150408/mm3/src/

**Comment by mmontvai** [comment] 2015-04-11 16:26
I did a clean lubuntu x86 install from scratch for MOAI environment with Oracle JDK 7, NDK r9d and latest Android SDK. 
Building was successful for `build-android.sh`, but it created only **armeabi** so I had to run again when the script was modified to build **armeabi-v7a first** (then x86 the same way). After running `build-linux.sh`, I applied the bash workaround suggested last time to `util/moaiutil`.
- `moaiutil host-android-gradle` still has its previous issue with applyConfigFile
- `moaiutil host create android-gradle` could be fixed (at least it creates an adroid gradle project)

First I would like to stress is that the error message this time was different:
updating template values
./util.lua:630: attempt to index local 'fp' (a nil value)
stack traceback:
    [C] in function '__index'
    ./util.lua:630 in function 'replaceInFile'
    ./util.lua:667 in function 'replaceInFiles'
    main.lua:269 in function 'configureHost'
    main.lua:333 in main chunk
    [C] in function 'dofile'
    moaiutil.lua:15 in main chunk

Tracing it back, the `util/host-android-gradle/main.lua` at line 288 requires a file named `local.properties` in the template directory which is missing. 
I created the missing `local.properties` file in `host-templates/android/studio/MoaiTemplate` containing two lines:
`sdk.dir=`
`ndk.dir=`
After this I could run the `moaiutil host create android-gradle` command successfully, a gradle project is created in the `hosts` directory as a result.
It seems that in the template gradle-wrapper.properties would be better to use http instead of https as later one causes errors.
Unfortunately running the build.sh still failed because it really wanted `android-21` and `build tools 21.1.2` exactly which is a bit strong in my opinion, but I think it is out of scope of this ticket.
It turned out that all ARCHs are required although I wanted to leave x86 out.

The build.sh still fails: 
aku_modules_android.cpp:28: error: undefined reference to 'AKUAndroidChartBoostAppFinalize()'
aku_modules_android.cpp:64: error: undefined reference to 'AKUAndroidChartBoostAppInitialize()', 
aku_modules_android.cpp:100:error: undefined reference to 'AKUAndroidChartBoostContextInitialize()', 

Currently I think we should close the issue as the original issue I reported was related to the ANT build, and currently the discussion is about moaiutil and gradle.

**Comment by halfnelson** [comment] 2015-04-11 20:24
Thanks for the detailed feedback. Just what we need thanks. I will look
into the build problem and advocate for adoption of CI so it stops happening

**Comment by halfnelson** [comment] 2015-04-12 12:56
if you try that pull request, it should all be a bit better.

**Comment by mmontvai** [comment] 2015-04-12 18:25
Thank you very much. 
Unfortunately I think I have no right to get the pull request you proposed, or I miss something as I am new to Git, could you help me?

**Comment by halfnelson** [comment] 2015-04-13 00:29
``` bash
git remote add moaiforge https://github.com/moaiforge/moai-sdk.git
git fetch moaiforge
git checkout pull_develop_update
```

**Comment by mmontvai** [comment] 2015-04-13 20:37
Thank you.
I tried it and it works: 
- `bin/build-android.sh` created libs for all platforms
- `moaiutil host init` then `moaiutil host create android-gradle` resulted a valid project structure
- `build.sh` created the debug.apk

Thank you very much, I think the build mechanism really works now :) 
(the `moaiutil host-android-gradle` still requires configFile)

I think we can close this issue if you agree.

**Closed as completed** 2016-04-29 13:19 UTC
